# Generated by Django 2.1.2 on 2018-12-10 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacists', '0003_auto_20181210_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='approved_comment',
        ),
    ]
