# Generated by Django 2.1.2 on 2018-12-11 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacists', '0006_auto_20181211_1746'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pharmacy',
        ),
    ]
