# Generated by Django 2.1.2 on 2018-12-13 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacists', '0007_delete_pharmacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='pharmacist',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='pharmacist',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
