# Generated by Django 2.1.2 on 2018-12-09 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0006_auto_20181127_1604'),
        ('orders', '0002_auto_20181209_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pharmacy',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacies.Pharmacy'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
