# Generated by Django 2.1.2 on 2018-11-20 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_stock'),
        ('pharmacies', '0003_auto_20181120_1359'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Membership',
            new_name='Stock',
        ),
    ]
