# Generated by Django 2.1.2 on 2018-11-27 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacies', '0005_auto_20181120_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.PositiveIntegerField(default=0)),
                ('pharmacist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='products',
            field=models.ManyToManyField(related_name='_pharmacy_products_+', through='pharmacies.Stock', to='products.Product'),
        ),
        migrations.AddField(
            model_name='employee',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacies.Pharmacy'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='pharmacists',
            field=models.ManyToManyField(related_name='_pharmacy_pharmacists_+', through='pharmacies.Employee', to=settings.AUTH_USER_MODEL),
        ),
    ]
