# Generated by Django 2.1.2 on 2018-12-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0006_auto_20181127_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
