# Generated by Django 2.1.2 on 2018-12-15 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0008_comments_rating'),
        ('accounts', '0005_auto_20181215_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='pharmacy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pharmacies.Pharmacy'),
        ),
    ]
